CREATE TABLE Utilisateur
(
Id INTEGER NOT NULL,
Nom VARCHAR(60) NOT NULL,
Prenom VARCHAR(60) NOT NULL,
Email VARCHAR(60) NOT NULL,
FK_IdCivilite INTEGER NOT NULL,
DateInscription DATE NOT NULL,
PRIMARY KEY (Id)
)

CREATE TABLE Civilite
(
Id INTEGER NOT NULL,
Label VARCHAR (50) NOT NULL,
PRIMARY KEY (Id)
)

CREATE TABLE CentreInteret
(
Id INTEGER NOT NULL,
Label VARCHAR (50) NOT NULL,
PRIMARY KEY (Id)
)

CREATE TABLE CentreInteret_Utilisateur
(
Id INTEGER NOT NULL,
FK_IdUtilisateur INT NOT NULL,
FK_IdCentreInterer INT NOT NULL,
PRIMARY KEY (Id)
)

CREATE TABLE Match
(
Id INTEGER NOT NULL,
FK_IdUtilisateur1 INTEGER NOT NULL,
FK_IdUtilisateur2 INTEGER NOT NULL,
PRIMARY KEY (Id)
)